baseURL = 'https://snlr308.github.io/'
languageCode = 'en-us'
title = 'snlr308'
theme = 'nostyleplease'

[params]
favicon = '/favicon.ico'

[params.theme_config]
isShowFooter = true

[module]
  [[module.mounts]]
    source = 'content'
    target = 'content'
  [[module.mounts]]
    source = 'README.md'
    target = 'content/_index.md'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'static'